spring:
  datasource:
    url: jdbc:sqlserver://MAVLT1548;databaseName=probeDB;encrypt=true;trustServerCertificate=true;
    username: Probe
    password: Admin@2026
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect

server:
  port: 8677
